# Generated by Django 4.2.7 on 2023-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_available_room_capacity_userinroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
