# Generated by Django 4.2.7 on 2023-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_tokenforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinroom',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
