# Generated by Django 4.2.7 on 2023-12-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_userinroom_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinroom',
            name='player_selected',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
