# Generated by Django 4.2.7 on 2023-12-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_userinroom_player_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinroom',
            old_name='player_selected',
            new_name='selected_player',
        ),
    ]
