# Generated by Django 4.2.7 on 2023-12-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_rename_player_selected_userinroom_selected_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinroom',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
