# Generated by Django 4.2.7 on 2023-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcontrol',
            name='playlist_cover',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playlistcontrol',
            name='playlist_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playlistcontrol',
            name='playlist_preview_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
