# Generated by Django 4.2.7 on 2023-11-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_name'),
        ('game', '0002_alter_playlistcontrol_playlist_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playlistcontrol')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
