# Generated by Django 4.2.7 on 2023-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_queuemusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemusic',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
