# Generated by Django 4.2.7 on 2023-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playlistcontrol_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontrol',
            name='playlist_artist',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
