# Generated by Django 4.2.7 on 2023-11-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playlistcontrol_playlist_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemusic',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.playlistcontrol'),
        ),
    ]
