# Generated by Django 4.2.7 on 2023-12-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_queuemusic_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemusic',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
