# Generated by Django 4.2.7 on 2023-12-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_queuemusic_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(default=15)),
            ],
        ),
    ]
