# Generated by Django 4.2.7 on 2023-12-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_name'),
        ('game', '0009_votetimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetimer',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
